### ISSUE TITLE
Switch to audited sha3 dependency

### ISSUE THREAD

**Issue by paulmillr** [joshstevens19/ethereum-bloom-filters#34]
js-sha3 can be replaced with audited https://github.com/paulmillr/noble-hashes, development of which has been funded by Ethereum Foundation. It is now more popular than js-sha3

**Comment by joshstevens19** [comment]
Happy to swap it out - open to a PR if not back from vacation next week and can do it 👍

**Comment by joshstevens19** [comment]
please cross check its a simple change > https://github.com/joshstevens19/ethereum-bloom-filters/pull/35 @paulmillr

**Comment by joshstevens19** [comment]
Merged deployment will happen tomorrow

**Comment by joshstevens19** [comment]
published 1.1.0
